base_url = "https://ryhl.io"
compile_sass = true
highlight_code = true
generate_rss = true

title = "Alice Ryhl"
description = "Personal website"

default_language = "en"

[extra]
keywords = "ryhl"

author = "Alice Ryhl"
author_email = "alice@ryhl.io"

sidebar_links = [
  { url = "/", text = "Home" },
  { url = "https://www.linkedin.com/in/aliceryhl/", text = "LinkedIn" },
  { url = "https://github.com/Darksonn/", text = "GitHub" },
  { url = "mailto:alice@ryhl.io", text = "Email" }
]
